device: cpu
use_debugger: True
thresholds: [0.4, 0.5, 0.75]
dataset: 
  json_mapper: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Pix2VoxFormer/dataset mapper/ShapeNet3DClone.json"
  data_path: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Data/Experimental/" 
  n_classes: 4


model:
  encoder:
    vit_version: b
    feature_dim:  768
    middle_dim: 1024
    latent_dim: 1024
    freeze: True
    pretrained: False
    blender: False #implement this shi
  
  lrelu_factor: 0.2
  use_bias: False


train:
  batch_size: 3
  epochs: 10
  epochs_till_merger: 3
  epochs_till_refiner: 250
  lr: 0.001
  reduce_lr_epochs: 150
  reduce_lr_factor: 0.5
  start_epoch: 0
  beta1: 0.9
  gamma: 0.5
  print_every: 50 #IN MINI-BATCHES
  save_every: 1 #IN EPOCHS
  output_dir: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Pix2VoxFormer/outputs"
  n_view_const: 10
  n_views_max: 15
  n_views_min: 6
  optimizer: adam
  load_from_pretrained: False

augmentation:
  brightness: 0.4
  saturation: 0.4
  contrast: 0.4