device: cpu
dataset: 
  config_path: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Pix2VoxFormer/dataset mapper/ShapeNet3DClone.json"
  data_path: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Data/Experimental/" 
  n_classes: 4
  # voxels_path: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Data/ShapeNetVox32"
  # images_path: "ShapeNet Rendering"
  
model:
  encoder:
    vit_version: b
    feature_dim:  768
    middle_dim: 1024
    latent_dim: 1024
    freeze: True
    pretrained: True
    blender: False #implement this shi
  
  lrelu_factor: 0.2
  use_bias: False


train:
  batch_size: 5
  epochs: 50
  lr: 0.001
  beta1: 0.9
  gamma: 0.5
  lr_milestones: [30, 60, 90]
  print_every: 5 #IN MINI-BATCHES
  save_weights_every: 5 #IN EPOCHS
  output_dir: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Pix2VoxFormer/outputs"
  n_view_const: 10
  n_views_max: 15
  n_views_min: 6
  optimizer: adam
  start_using_refiner = 
  

augmentation:
  brightness: 0.4
  saturation: 0.4
  contrast: 0.4