device: cpu
use_debugger: True
dataset: 
  json_mapper: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Pix2VoxFormer/dataset mapper/ShapeNet3DClone.json"
  data_path: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Data/Experimental/" 
  n_classes: 4


model:
  encoder:
    vit_version: b
    feature_dim:  768
    middle_dim: 1024
    latent_dim: 1024
    freeze: True
    pretrained: False
    blender: False #implement this shi
  
  lrelu_factor: 0.2
  use_bias: False


train:
  batch_size: 5
  epochs: 200
  lr: 0.0001
  beta1: 0.9
  gamma: 0.5
  lr_milestones: [30, 60, 90]
  print_every: 50 #IN MINI-BATCHES
  save_weights_every: 5 #IN EPOCHS
  output_dir: "/home/mahmoud-sayed/Desktop/Graduation Project/current/Pix2VoxFormer/outputs"
  n_view_const: 10
  n_views_max: 15
  n_views_min: 6
  optimizer: adam
  epochs_till_merger: 100
  epochs_till_refiner: 130
  

augmentation:
  brightness: 0.4
  saturation: 0.4
  contrast: 0.4