device: cuda
use_debugger: True
thresholds: [0.3, 0.5, 0.75]
dataset: 
  json_mapper: "/kaggle/working/3D-Reconstruction-GP/dataset mapper/ShapeNet.json"
  data_path: "/kaggle/input/shapenet" 
  n_classes: 12


model:
  encoder:
    vit_version: b
    feature_dim:  768
    middle_dim: 1024
    latent_dim: 1024
    freeze: True
    pretrained: True
    blender: False #implement this shi
  
  lrelu_factor: 0.2
  use_bias: True


train:
  batch_size: 32
  epochs: 350
  epochs_till_merger: 250
  # epochs_till_refiner: 250
  lr: 0.001
  reduce_lr_epochs: 150
  reduce_lr_factor: 0.5
  start_epoch: 0
  beta1: 0.9
  gamma: 0.5
  print_every: 50 #IN MINI-BATCHES
  save_every: 1 #IN EPOCHS
  output_dir: "/kaggle/working/"
  n_view_const: 10
  n_views_max: 15
  n_views_min: 6
  optimizer: adam
  load_from_pretrained: False

augmentation:
  brightness: 0.2
  saturation: 0.2
  contrast: 0.2